// Single source of truth for the calculator list — consumed by the
// homepage card grid and the header's calculator menu, so adding or
// re-labelling a calculator never means updating two places in sync.
// `category` groups the header menu (and any future homepage grouping) —
// PaisaCalc-specific groupings, not calculator.net's own category
// scheme. Fitness & Health calculators (added after the site expanded
// beyond pure personal-finance) live in their own category rather than
// being forced into a finance grouping.
export const CALCULATOR_CATEGORIES = [
  "Loans & EMI",
  "Tax",
  "Savings & Investments",
  "Income & Planning",
  "Fitness & Health",
  "Math",
  "Date & Time",
  "Home & Construction",
  "Conversions & Science",
  "Tech Tools",
  "Everyday & Lifestyle",
  "Weather",
  "Automotive",
] as const;

export type CalculatorCategory = (typeof CALCULATOR_CATEGORIES)[number];

export type Calculator = {
  href: string;
  label: string;
  description: string;
  image: string;
  imagePosition: string;
  category: CalculatorCategory;
};

// Shared between the homepage directory (section ids) and individual
// calculator pages (breadcrumb links back to that section) — one
// definition so the two can never drift apart.
export function categorySlug(category: CalculatorCategory): string {
  return `category-${category.replace(/\s+/g, "-")}`;
}

export const CALCULATORS = [
  {
    href: "/home-loan-emi/",
    label: "Home loan EMI",
    description: "Monthly EMI and the full amortisation schedule.",
    image: "/images/hero-house.webp",
    imagePosition: "60% 40%",
    category: "Loans & EMI",
  },
  {
    href: "/car-loan-emi/",
    label: "Car loan EMI",
    description: "Monthly EMI and repayment schedule for a new or used car.",
    image: "/images/hero-highway.webp",
    imagePosition: "center 30%",
    category: "Loans & EMI",
  },
  {
    href: "/loan-prepayment/",
    label: "Loan prepayment impact",
    description: "How much interest a lump-sum prepayment actually saves.",
    image: "/images/hero-house.webp",
    imagePosition: "30% 60%",
    category: "Loans & EMI",
  },
  {
    href: "/home-loan-eligibility/",
    label: "Home loan eligibility",
    description: "The maximum loan your income and FOIR actually support.",
    image: "/images/hero-house.webp",
    imagePosition: "40% 55%",
    category: "Loans & EMI",
  },
  {
    href: "/personal-loan-emi/",
    label: "Personal loan EMI",
    description: "Monthly EMI on an unsecured personal loan.",
    image: "/images/hero-rupee.webp",
    imagePosition: "55% center",
    category: "Loans & EMI",
  },
  {
    href: "/education-loan-emi/",
    label: "Education loan EMI",
    description: "EMI after the moratorium, including capitalised interest.",
    image: "/images/hero-pen.webp",
    imagePosition: "70% 35%",
    category: "Loans & EMI",
  },
  {
    href: "/credit-card-payoff/",
    label: "Credit card payoff",
    description: "How many months to clear a balance, and what it costs.",
    image: "/images/hero-coins.webp",
    imagePosition: "70% 55%",
    category: "Loans & EMI",
  },
  {
    href: "/income-tax/",
    label: "Income tax: old vs new regime",
    description: "Compare both regimes side by side and see which costs less.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 70%",
    category: "Tax",
  },
  {
    href: "/hra-exemption/",
    label: "HRA exemption",
    description: "The three-way minimum rule, worked out for your numbers.",
    image: "/images/hero-skyline.webp",
    imagePosition: "center 55%",
    category: "Tax",
  },
  {
    href: "/capital-gains/",
    label: "Capital gains tax",
    description: "Equity and property, including the indexation choice.",
    image: "/images/hero-chart.webp",
    imagePosition: "70% center",
    category: "Tax",
  },
  {
    href: "/gst-calculator/",
    label: "GST calculator",
    description: "Add or remove GST across the current 0/3/5/18/40% slabs.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 40%",
    category: "Tax",
  },
  {
    href: "/sip-returns/",
    label: "SIP returns",
    description: "Project a monthly SIP's future value, with an optional step-up.",
    image: "/images/hero-chart.webp",
    imagePosition: "30% center",
    category: "Savings & Investments",
  },
  {
    href: "/fd-calculator/",
    label: "FD calculator",
    description: "Fixed deposit maturity value with quarterly compounding.",
    image: "/images/hero-coins.webp",
    imagePosition: "center 45%",
    category: "Savings & Investments",
  },
  {
    href: "/rd-calculator/",
    label: "RD calculator",
    description: "Recurring deposit maturity value with quarterly compounding.",
    image: "/images/hero-rupee.webp",
    imagePosition: "80% center",
    category: "Savings & Investments",
  },
  {
    href: "/ppf-calculator/",
    label: "PPF calculator",
    description: "Public Provident Fund maturity value over the 15-year lock-in.",
    image: "/images/hero-pen.webp",
    imagePosition: "30% 40%",
    category: "Savings & Investments",
  },
  {
    href: "/nps-calculator/",
    label: "NPS calculator",
    description: "Retirement corpus and the lump-sum/annuity split at exit.",
    image: "/images/hero-skyline.webp",
    imagePosition: "center 40%",
    category: "Savings & Investments",
  },
  {
    href: "/in-hand-salary/",
    label: "In-hand salary from CTC",
    description: "Real take-home pay, after PF, gratuity, and tax.",
    image: "/images/hero-coins.webp",
    imagePosition: "center 30%",
    category: "Income & Planning",
  },
  {
    href: "/gratuity/",
    label: "Gratuity",
    description: "What you're owed, and how much of it is tax-free.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 30%",
    category: "Income & Planning",
  },
  {
    href: "/inflation-calculator/",
    label: "Inflation calculator",
    description: "What today's ₹ will actually cost in the future.",
    image: "/images/hero-chart.webp",
    imagePosition: "center 60%",
    category: "Income & Planning",
  },
  {
    href: "/debt-to-income-ratio/",
    label: "Debt-to-income ratio",
    description: "What share of your income is already committed to debt.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 55%",
    category: "Income & Planning",
  },
  {
    href: "/savings-goal/",
    label: "Savings goal",
    description: "Monthly saving needed to hit a target amount by a date.",
    image: "/images/hero-coins.webp",
    imagePosition: "40% 40%",
    category: "Savings & Investments",
  },
  {
    href: "/rent-vs-buy/",
    label: "Rent vs. buy",
    description: "Which comes out ahead over the years you'll actually stay.",
    image: "/images/hero-house.webp",
    imagePosition: "50% 50%",
    category: "Income & Planning",
  },
  {
    href: "/debt-consolidation/",
    label: "Debt consolidation",
    description: "Whether rolling debts into one loan actually saves money.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 45%",
    category: "Loans & EMI",
  },
  {
    href: "/rent-affordability/",
    label: "Rent affordability",
    description: "How much rent actually fits your budget.",
    image: "/images/hero-skyline.webp",
    imagePosition: "center 50%",
    category: "Income & Planning",
  },
  {
    href: "/real-estate-returns/",
    label: "Real estate returns",
    description: "Net profit and annualised return from buying and later selling a property.",
    image: "/images/hero-house.webp",
    imagePosition: "70% 40%",
    category: "Income & Planning",
  },
  {
    href: "/balance-transfer/",
    label: "Home loan balance transfer",
    description: "Whether switching lenders for a lower rate actually pays off.",
    image: "/images/hero-house.webp",
    imagePosition: "40% 55%",
    category: "Loans & EMI",
  },
  {
    href: "/rental-yield/",
    label: "Rental yield",
    description: "Gross/net yield and real monthly cash flow after the EMI.",
    image: "/images/hero-house.webp",
    imagePosition: "30% 60%",
    category: "Income & Planning",
  },
  {
    href: "/apr-calculator/",
    label: "APR calculator",
    description: "The real annual rate once the processing fee is factored in.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 60%",
    category: "Loans & EMI",
  },
  {
    href: "/loan-against-property/",
    label: "Loan against property",
    description: "EMI on a loan against a property you already own.",
    image: "/images/hero-house.webp",
    imagePosition: "45% 50%",
    category: "Loans & EMI",
  },
  {
    href: "/home-loan-overdraft/",
    label: "Home loan overdraft",
    description: "How much parking surplus savings against the loan actually saves.",
    image: "/images/hero-house.webp",
    imagePosition: "55% 45%",
    category: "Loans & EMI",
  },
  {
    href: "/down-payment-calculator/",
    label: "Down payment",
    description: "How much you need, and how long it takes to save it.",
    image: "/images/hero-house.webp",
    imagePosition: "35% 65%",
    category: "Income & Planning",
  },
  {
    href: "/cashback-vs-lowrate/",
    label: "Cash back vs. low interest",
    description: "Which car financing offer actually costs less.",
    image: "/images/hero-highway.webp",
    imagePosition: "center 35%",
    category: "Loans & EMI",
  },
  {
    href: "/auto-lease/",
    label: "Auto lease",
    description: "Monthly lease payment, split into its two real charges.",
    image: "/images/hero-highway.webp",
    imagePosition: "center 45%",
    category: "Loans & EMI",
  },
  {
    href: "/interest-calculator/",
    label: "Interest calculator",
    description: "Compound interest, any rate, any compounding frequency.",
    image: "/images/hero-coins.webp",
    imagePosition: "center 40%",
    category: "Savings & Investments",
  },
  {
    href: "/simple-interest/",
    label: "Simple interest",
    description: "I = P × R × T — no compounding.",
    image: "/images/hero-coins.webp",
    imagePosition: "center 55%",
    category: "Savings & Investments",
  },
  {
    href: "/bond-calculator/",
    label: "Bond calculator",
    description: "What a bond is actually worth today, at the market yield.",
    image: "/images/hero-chart.webp",
    imagePosition: "center 50%",
    category: "Savings & Investments",
  },
  {
    href: "/mutual-fund-calculator/",
    label: "Mutual fund calculator",
    description: "What the expense ratio actually costs you, in rupees.",
    image: "/images/hero-chart.webp",
    imagePosition: "30% center",
    category: "Savings & Investments",
  },
  {
    href: "/average-return/",
    label: "Average return",
    description: "The gap between average return and what you actually earn.",
    image: "/images/hero-chart.webp",
    imagePosition: "70% center",
    category: "Savings & Investments",
  },
  {
    href: "/irr-calculator/",
    label: "IRR calculator",
    description: "The real rate of return on uneven cash flows.",
    image: "/images/hero-chart.webp",
    imagePosition: "center 55%",
    category: "Savings & Investments",
  },
  {
    href: "/roi-calculator/",
    label: "ROI calculator",
    description: "Total and annualised return on any investment.",
    image: "/images/hero-chart.webp",
    imagePosition: "center 45%",
    category: "Savings & Investments",
  },
  {
    href: "/payback-period/",
    label: "Payback period",
    description: "How long until an investment pays for itself.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 50%",
    category: "Savings & Investments",
  },
  {
    href: "/present-value/",
    label: "Present value",
    description: "What a future amount is worth today.",
    image: "/images/hero-chart.webp",
    imagePosition: "center 40%",
    category: "Savings & Investments",
  },
  {
    href: "/future-value/",
    label: "Future value",
    description: "What a lump sum today grows to.",
    image: "/images/hero-chart.webp",
    imagePosition: "center 60%",
    category: "Savings & Investments",
  },
  {
    href: "/eps-pension/",
    label: "EPS pension",
    description: "Your monthly pension under EPFO's actual formula.",
    image: "/images/hero-skyline.webp",
    imagePosition: "center 45%",
    category: "Income & Planning",
  },
  {
    href: "/annuity-payout/",
    label: "Annuity payout",
    description: "How much a lump sum can pay out every month.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 40%",
    category: "Income & Planning",
  },
  {
    href: "/credit-card-minimum/",
    label: "Credit card minimum payment",
    description: "What paying only the minimum actually costs.",
    image: "/images/hero-coins.webp",
    imagePosition: "70% 55%",
    category: "Loans & EMI",
  },
  {
    href: "/debt-payoff/",
    label: "Debt payoff strategy",
    description: "Avalanche vs. snowball — which saves more interest.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 35%",
    category: "Loans & EMI",
  },
  {
    href: "/college-cost/",
    label: "College cost",
    description: "What a course will actually cost by enrollment.",
    image: "/images/hero-pen.webp",
    imagePosition: "center 35%",
    category: "Income & Planning",
  },
  {
    href: "/depreciation-calculator/",
    label: "Depreciation calculator",
    description: "WDV vs. SLM — India's two depreciation methods.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 50%",
    category: "Income & Planning",
  },
  {
    href: "/business-loan/",
    label: "Business loan",
    description: "EMI at typical MSME loan rates and tenures.",
    image: "/images/hero-desk.webp",
    imagePosition: "30% 40%",
    category: "Loans & EMI",
  },
  {
    href: "/margin-calculator/",
    label: "Margin calculator",
    description: "Margin vs. markup — the same profit, two numbers.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 40%",
    category: "Income & Planning",
  },
  {
    href: "/discount-calculator/",
    label: "Discount calculator",
    description: "The final price, and exactly what you save.",
    image: "/images/hero-coins.webp",
    imagePosition: "center 45%",
    category: "Income & Planning",
  },
  {
    href: "/budget-calculator/",
    label: "Budget calculator",
    description: "Needs, wants, and savings — the 50/30/20 rule.",
    image: "/images/hero-rupee.webp",
    imagePosition: "center 40%",
    category: "Income & Planning",
  },
  {
    href: "/commission-calculator/",
    label: "Commission calculator",
    description: "Commission earned on a sale, and what's left.",
    image: "/images/hero-desk.webp",
    imagePosition: "center 45%",
    category: "Income & Planning",
  },
  {
    href: "/bmi-calculator/",
    label: "BMI calculator",
    description: "Body Mass Index using the Asian-specific WHO cutoffs.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 40%",
    category: "Fitness & Health",
  },
  {
    href: "/calorie-calculator/",
    label: "Calorie calculator",
    description: "Daily calorie target to lose, maintain, or gain weight.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 55%",
    category: "Fitness & Health",
  },
  {
    href: "/body-fat-calculator/",
    label: "Body fat calculator",
    description: "Body fat percentage from tape measurements.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 45%",
    category: "Fitness & Health",
  },
  {
    href: "/bmr-calculator/",
    label: "BMR calculator",
    description: "Calories burned at complete rest, Mifflin-St Jeor.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/ideal-weight-calculator/",
    label: "Ideal weight calculator",
    description: "Four clinical formulas, shown side by side.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 40%",
    category: "Fitness & Health",
  },
  {
    href: "/pace-calculator/",
    label: "Pace calculator",
    description: "Running pace and speed from distance and time.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 60%",
    category: "Fitness & Health",
  },
  {
    href: "/lean-body-mass/",
    label: "Lean body mass calculator",
    description: "Lean mass from height and weight, the Boer formula.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/healthy-weight/",
    label: "Healthy weight calculator",
    description: "The healthy weight range for your height.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 55%",
    category: "Fitness & Health",
  },
  {
    href: "/calories-burned/",
    label: "Calories burned calculator",
    description: "Calories burned during an activity, by MET value.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 45%",
    category: "Fitness & Health",
  },
  {
    href: "/one-rep-max/",
    label: "One rep max calculator",
    description: "Estimated 1RM from a sub-maximal set, Epley and Brzycki.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/target-heart-rate/",
    label: "Target heart rate calculator",
    description: "Training zones from age and resting heart rate, Karvonen formula.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 55%",
    category: "Fitness & Health",
  },
  {
    href: "/pregnancy-calculator/",
    label: "Pregnancy calculator",
    description: "How far along you are and your due date, from your LMP.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 45%",
    category: "Fitness & Health",
  },
  {
    href: "/pregnancy-weight-gain/",
    label: "Pregnancy weight gain calculator",
    description: "Recommended weight gain range for your pre-pregnancy BMI, IOM.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 55%",
    category: "Fitness & Health",
  },
  {
    href: "/pregnancy-conception/",
    label: "Pregnancy conception calculator",
    description: "When conception likely happened, for a confirmed pregnancy.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 45%",
    category: "Fitness & Health",
  },
  {
    href: "/due-date-calculator/",
    label: "Due date calculator",
    description: "Estimated due date from your last period or a conception date.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 40%",
    category: "Fitness & Health",
  },
  {
    href: "/ovulation-calculator/",
    label: "Ovulation calculator",
    description: "Predicted ovulation date and fertile window, next cycle.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/conception-calculator/",
    label: "Conception calculator",
    description: "Estimated conception date, worked back from a due or birth date.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 55%",
    category: "Fitness & Health",
  },
  {
    href: "/period-calculator/",
    label: "Period calculator",
    description: "Predicted dates for your next several menstrual cycles.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/macro-calculator/",
    label: "Macro calculator",
    description: "Daily protein, carb, and fat targets in grams, diet-plan presets.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/carbohydrate-calculator/",
    label: "Carbohydrate calculator",
    description: "Recommended daily carb range in grams, US Dietary Guidelines.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/protein-calculator/",
    label: "Protein calculator",
    description: "Daily protein target from bodyweight and activity level.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 55%",
    category: "Fitness & Health",
  },
  {
    href: "/fat-intake-calculator/",
    label: "Fat intake calculator",
    description: "Recommended daily fat range in grams, plus a saturated fat cap.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/tdee-calculator/",
    label: "TDEE calculator",
    description: "Total daily energy expenditure at every activity level.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/gfr-calculator/",
    label: "GFR calculator",
    description: "Estimated kidney filtration rate, CKD-EPI 2021 equation.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/body-type-calculator/",
    label: "Body type calculator",
    description: "Ectomorph, mesomorph, or endomorph frame size.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 55%",
    category: "Fitness & Health",
  },
  {
    href: "/body-surface-area/",
    label: "Body surface area calculator",
    description: "BSA from height and weight, Mosteller and DuBois formulas.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/bac-calculator/",
    label: "BAC calculator",
    description: "Estimated blood alcohol content, Widmark formula.",
    image: "/images/hero-watch.webp",
    imagePosition: "center 50%",
    category: "Fitness & Health",
  },
  {
    href: "/fraction-calculator/",
    label: "Fraction calculator",
    description: "Add, subtract, multiply, or divide fractions.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/percentage-calculator/",
    label: "Percentage calculator",
    description: "X% of Y, X as a % of Y, or what Y is.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/percent-error-calculator/",
    label: "Percent error calculator",
    description: "How far a measured value is from the theoretical value.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/exponent-calculator/",
    label: "Exponent calculator",
    description: "Any base to any power, negative or fractional exponents.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/rounding-calculator/",
    label: "Rounding calculator",
    description: "Round to any decimal place, nearest, up, or down.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/root-calculator/",
    label: "Root calculator",
    description: "Square root, cube root, or any nth root.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/ratio-calculator/",
    label: "Ratio calculator",
    description: "Simplify ratios and solve proportions.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/lcm-calculator/",
    label: "LCM calculator",
    description: "Least common multiple via prime factorisation.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/gcf-calculator/",
    label: "GCF calculator",
    description: "Greatest common factor via prime factorisation.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/factor-calculator/",
    label: "Factor calculator",
    description: "Every factor of a number, plus prime factorization.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/scientific-notation-calculator/",
    label: "Scientific notation calculator",
    description: "Decimal to scientific notation, both directions.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/big-number-calculator/",
    label: "Big number calculator",
    description: "Arbitrary-precision integer arithmetic.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/binary-calculator/",
    label: "Binary calculator",
    description: "Decimal to binary, both directions.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/hex-calculator/",
    label: "Hex calculator",
    description: "Decimal to hexadecimal, both directions.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/scientific-calculator/",
    label: "Scientific calculator",
    description: "Operators, trig functions, roots, and logarithms.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/random-number-generator/",
    label: "Random number generator",
    description: "Whole numbers or decimals within a range.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/half-life-calculator/",
    label: "Half-life calculator",
    description: "Remaining quantity from exponential decay.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/quadratic-formula-calculator/",
    label: "Quadratic formula calculator",
    description: "Solve ax² + bx + c = 0, including complex roots.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/log-calculator/",
    label: "Log calculator",
    description: "Logarithm of a number to any base.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/matrix-calculator/",
    label: "Matrix calculator",
    description: "Add, subtract, or multiply 2×2 matrices.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/standard-deviation-calculator/",
    label: "Standard deviation calculator",
    description: "Mean, variance, and standard deviation of a data set.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/number-sequence-calculator/",
    label: "Number sequence calculator",
    description: "Generate arithmetic or geometric sequences.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/sample-size-calculator/",
    label: "Sample size calculator",
    description: "Minimum survey sample size for your confidence level.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/probability-calculator/",
    label: "Probability calculator",
    description: "P(A and B), P(A or B), P(not A) for independent events.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/statistics-calculator/",
    label: "Statistics calculator",
    description: "Full descriptive statistics report for a data set.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/mean-median-mode-calculator/",
    label: "Mean, median, mode, range calculator",
    description: "The four basic descriptive statistics, in one result.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/permutation-combination-calculator/",
    label: "Permutation and combination calculator",
    description: "nPr and nCr — ways to choose r items from n.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/z-score-calculator/",
    label: "Z-score calculator",
    description: "Standard deviations from the mean, and percentile.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/confidence-interval-calculator/",
    label: "Confidence interval calculator",
    description: "Confidence interval for a population mean.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/triangle-calculator/",
    label: "Triangle calculator",
    description: "Area, perimeter, and angles from three sides.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/volume-calculator/",
    label: "Volume calculator",
    description: "Cube, box, sphere, cylinder, or cone.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/slope-calculator/",
    label: "Slope calculator",
    description: "Slope, line equation, and distance between two points.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/area-calculator/",
    label: "Area calculator",
    description: "Square, rectangle, circle, triangle, or trapezoid.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/distance-calculator/",
    label: "Distance calculator",
    description: "Straight-line distance between two points.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/circle-calculator/",
    label: "Circle calculator",
    description: "Diameter, circumference, and area from radius.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/surface-area-calculator/",
    label: "Surface area calculator",
    description: "Cube, box, sphere, cylinder, or cone.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/pythagorean-theorem-calculator/",
    label: "Pythagorean theorem calculator",
    description: "Solve a² + b² = c² for any side.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/right-triangle-calculator/",
    label: "Right triangle calculator",
    description: "Hypotenuse, area, perimeter, and angles.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Math",
  },
  {
    href: "/age-calculator/",
    label: "Age calculator",
    description: "Exact age in years, months, and days.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/date-calculator/",
    label: "Date calculator",
    description: "Add or subtract years, months, weeks, and days.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/time-calculator/",
    label: "Time calculator",
    description: "Add or subtract clock-time durations.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/hours-calculator/",
    label: "Hours calculator",
    description: "Total hours worked, start to end time.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/time-card-calculator/",
    label: "Time card calculator",
    description: "Weekly hours, regular and overtime.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/time-zone-calculator/",
    label: "Time zone calculator",
    description: "Convert a time between UTC offsets.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/time-duration-calculator/",
    label: "Time duration calculator",
    description: "Precise duration between two datetimes.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/day-counter/",
    label: "Day counter",
    description: "Days between two dates, weekdays vs weekends.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/day-of-week-calculator/",
    label: "Day of the week calculator",
    description: "What day any date falls on.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Date & Time",
  },
  {
    href: "/concrete-calculator/",
    label: "Concrete calculator",
    description: "Slab volume and bags needed.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/btu-calculator/",
    label: "BTU calculator",
    description: "AC or heater sizing for a room.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/square-footage-calculator/",
    label: "Square footage calculator",
    description: "Room area plus material cost estimate.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/stair-calculator/",
    label: "Stair calculator",
    description: "Riser, tread, and stringer length.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/roofing-calculator/",
    label: "Roofing calculator",
    description: "Roof area and shingle bundles needed.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/tile-calculator/",
    label: "Tile calculator",
    description: "Tiles needed, with waste allowance.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/mulch-calculator/",
    label: "Mulch calculator",
    description: "Mulch needed by area and depth.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/gravel-calculator/",
    label: "Gravel calculator",
    description: "Gravel volume and weight needed.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Home & Construction",
  },
  {
    href: "/height-calculator/",
    label: "Height calculator",
    description: "Predicted adult height for a child.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/conversion-calculator/",
    label: "Conversion calculator",
    description: "Length units, metric and imperial.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/gdp-calculator/",
    label: "GDP calculator",
    description: "Gross Domestic Product, expenditure approach.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/density-calculator/",
    label: "Density calculator",
    description: "Density from mass and volume.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/mass-calculator/",
    label: "Mass calculator",
    description: "Mass from density and volume.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/weight-calculator/",
    label: "Weight calculator",
    description: "Weight (gravity's force) on Earth and beyond.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/speed-calculator/",
    label: "Speed calculator",
    description: "Solve for speed, distance, or time.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/molarity-calculator/",
    label: "Molarity calculator",
    description: "Solve for molarity, moles, or volume.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/molecular-weight-calculator/",
    label: "Molecular weight calculator",
    description: "From a chemical formula, IUPAC weights.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Conversions & Science",
  },
  {
    href: "/roman-numeral-converter/",
    label: "Roman numeral converter",
    description: "Decimal to Roman, both directions.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/ip-subnet-calculator/",
    label: "IP subnet calculator",
    description: "Network, broadcast, and host range for CIDR.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/password-generator/",
    label: "Password generator",
    description: "Random passwords, generated in your browser.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/bandwidth-calculator/",
    label: "Bandwidth calculator",
    description: "File transfer time from size and speed.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/base64-encode-decode/",
    label: "Base64 encode / decode",
    description: "In your browser, full Unicode support.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/url-encode-decode/",
    label: "URL encode / decode",
    description: "Percent-encoding, in your browser.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/ohms-law-calculator/",
    label: "Ohm's law calculator",
    description: "V = I × R, solve for any one.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/resistor-calculator/",
    label: "Resistor calculator",
    description: "4-band color code to resistance value.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/voltage-drop-calculator/",
    label: "Voltage drop calculator",
    description: "Voltage lost over a wire run.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/electricity-calculator/",
    label: "Electricity calculator",
    description: "Appliance running cost, daily to yearly.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Tech Tools",
  },
  {
    href: "/gpa-calculator/",
    label: "GPA calculator",
    description: "Weighted GPA on the 4.0 scale.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/grade-calculator/",
    label: "Grade calculator",
    description: "Overall grade from weighted scores.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/wind-chill-calculator/",
    label: "Wind chill calculator",
    description: "How cold it actually feels.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Weather",
  },
  {
    href: "/heat-index-calculator/",
    label: "Heat index calculator",
    description: "How hot it actually feels.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Weather",
  },
  {
    href: "/dew-point-calculator/",
    label: "Dew point calculator",
    description: "From temperature and relative humidity.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Weather",
  },
  {
    href: "/fuel-cost-calculator/",
    label: "Fuel cost calculator",
    description: "Total fuel cost for a trip.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Automotive",
  },
  {
    href: "/gas-mileage-calculator/",
    label: "Gas mileage calculator",
    description: "Actual fuel efficiency from a real trip.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Automotive",
  },
  {
    href: "/horsepower-calculator/",
    label: "Horsepower calculator",
    description: "From torque and engine RPM.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Automotive",
  },
  {
    href: "/engine-horsepower-calculator/",
    label: "Engine horsepower calculator",
    description: "From weight and quarter-mile trap speed.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Automotive",
  },
  {
    href: "/mileage-calculator/",
    label: "Mileage calculator",
    description: "Travel reimbursement for business miles.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Automotive",
  },
  {
    href: "/tire-size-calculator/",
    label: "Tire size calculator",
    description: "Diameter, circumference, and revs per mile.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Automotive",
  },
  {
    href: "/bra-size-calculator/",
    label: "Bra size calculator",
    description: "From underbust and bust measurements.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/shoe-size-conversion/",
    label: "Shoe size conversion",
    description: "US, UK, and EU sizing.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/tip-calculator/",
    label: "Tip calculator",
    description: "Tip amount, total, and per-person split.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/golf-handicap-calculator/",
    label: "Golf handicap calculator",
    description: "Handicap differential for one round.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/sleep-calculator/",
    label: "Sleep calculator",
    description: "Optimal bedtime, 90-minute cycles.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/dice-roller/",
    label: "Dice roller",
    description: "Any number of dice, any number of sides.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
  {
    href: "/love-calculator/",
    label: "Love calculator",
    description: "Just for fun — not scientific.",
    image: "/images/hero-pen.webp",
    imagePosition: "center",
    category: "Everyday & Lifestyle",
  },
] as const satisfies ReadonlyArray<Calculator>;
